#
# Name                    Version                   Build  Channel
appdirs                   1.4.4                    pypi_0    pypi
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
black                     20.8b1                   pypi_0    pypi
bleach                    3.3.0                    pypi_0    pypi
build                     0.3.0                    pypi_0    pypi
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coverage                  5.5                      pypi_0    pypi
docspec                   0.2.1                    pypi_0    pypi
docspec-python            0.1.0                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
jinja2                    2.11.3                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
keyring                   22.3.0                   pypi_0    pypi
libcxx                    11.0.1               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
livereload                2.6.3                    pypi_0    pypi
lunr                      0.5.9                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
mkdocs                    1.1.2                    pypi_0    pypi
more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
mypy-extensions           0.4.3                    pypi_0    pypi
ncurses                   6.2                  h2e338ed_4    conda-forge
nltk                      3.5                      pypi_0    pypi
nr-collections            0.1.1                    pypi_0    pypi
nr-databind-core          0.0.22                   pypi_0    pypi
nr-databind-json          0.0.14                   pypi_0    pypi
nr-fs                     1.6.3                    pypi_0    pypi
nr-interface              0.0.4                    pypi_0    pypi
nr-metaclass              0.0.6                    pypi_0    pypi
nr-parsing-date           0.4.4                    pypi_0    pypi
nr-pylang-utils           0.0.4                    pypi_0    pypi
nr-stream                 0.0.5                    pypi_0    pypi
nr-sumtype                0.0.4                    pypi_0    pypi
nr-utils-re               0.1.1                    pypi_0    pypi
openssl                   1.1.1j               hbcf498f_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pathspec                  0.8.1                    pypi_0    pypi
pep517                    0.9.1                    pypi_0    pypi
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.7.0                    pypi_0    pypi
pluggy                    0.13.1           py39h6e9494a_4    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pygments                  2.8.0                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pytest                    6.2.2            py39h6e9494a_0    conda-forge
pytest-mock               3.5.1                    pypi_0    pypi
python                    3.9.2           h2502468_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.0                  h0678c8f_2    conda-forge
readme-renderer           29.0                     pypi_0    pypi
regex                     2020.11.13               pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-toolbelt         0.9.1                    pypi_0    pypi
rfc3986                   1.4.0                    pypi_0    pypi
setuptools                54.0.0                   pypi_0    pypi
setuptools-scm-git-archive 1.1                      pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sqlite                    3.34.0               h17101e1_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1                      pypi_0    pypi
tqdm                      4.58.0                   pypi_0    pypi
twine                     3.3.0                    pypi_0    pypi
typed-ast                 1.4.2                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.3                   pypi_0    pypi
versioneer                0.19                     pypi_0    pypi
watchdog                  2.0.2                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
