# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - name: Set up Python ${{ matrix.python-version }} with Rye
      run: |
        rye pin python ${{ matrix.python-version }}
    - name: Install dependencies with Rye
      run: |
        rye sync --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        rye run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        rye run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest and create report
      run: |
        rye run coverage run -m pytest
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true