name: Release Drafter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.15.0
